server:
  port: 8762

spring:
  application:
    name: zuul-server

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

zuul:
  routes:
    my-route-1:
      path: /my-route-1/**
      #url: http://localhost:9081/
      serviceId: MY-ROUTE-1
      sensitiveHeaders:
      stripPrefix: true
    my-route-2:
      path: /my-route2/**
      url: http://localhost:9082/
      sensitiveHeaders:
        stripPrefix: true
  #http://github.com/spring-cloud/spring-cloud-netflix/issues/904
  add-host-header: true
  add-proxy-headers: true