spring:
  application:
    name: MY-ROUTE-1

server:
  port: 9081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true